name: DposFinder
channels:
  - bioconda
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=22.3.1
  - pip:
    - numpy==1.21.6
    - pandas==1.3.5
    - fair-esm==2.0.0
    - scikit-learn==1.0.2
    - torch==1.9.1+cu102
    - torchaudio==0.9.1
    - torchvision==0.10.1+cu102
    - einops==0.6.1
    - tensorboardx==2.6.2.2
    - matplotlib==3.5.3
    - logomaker==0.8
    - seaborn==0.12.2